# Generated by Django 3.1.5 on 2021-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.FileField(default='', upload_to='static/'),
        ),
    ]
